# Generated by Django 5.2.6 on 2025-09-30 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название товара", max_length=255, verbose_name="Название"),
                ),
                ("price", models.PositiveIntegerField(help_text="Введите цену товара", verbose_name="Цена")),
                ("description", models.TextField(help_text="Введите описание товара", verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Автоматическое время создания",
                        verbose_name="Время и дата создания",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Введите ID автора объявления",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель объявления",
                    ),
                ),
            ],
            options={
                "verbose_name": "объявление",
                "verbose_name_plural": "объявления",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Автоматическое время создания",
                        verbose_name="Время и дата создания",
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Введите ID объявления",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="buyrate.ad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Введите ID автора отзыва",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель отзыва",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
            },
        ),
    ]
